version: '3.8'
services:
  crushftp-init:
    image: 'crushftp/crushftp11:latest-dev'
    container_name: crushftp-init
    environment:
      - INIT=true
    volumes:
    - ./CrushFTP11/:/app/CrushFTP11
    - ./passfile:/tmp/passfile
    entrypoint: ["/bin/sh", "-c", "/entrypoint.sh"]
    user: "${UID}:${GID}"
  crushftp:
    image: 'crushftp/crushftp11:latest'
    container_name: crushftp
    ports:
      - '8081:8080'
      - '9091:9090'
      - '8443:443'
    volumes:
    - ./CrushFTP11/:/app/CrushFTP11
    - ./passfile:/tmp/passfile
    environment:
      - passfile=/tmp/passfile
    working_dir: "/app/CrushFTP11"
    entrypoint: ["java", "-Ddir=/app/CrushFTP11", "-Xmx512M", "-jar", "/app/CrushFTP11/plugins/lib/CrushFTPJarProxy.jar", "-ad", "crushadmin", "passfile"]
    user: "${UID}:${GID}"
    depends_on:
      crushftp-init:
        condition: service_completed_successfully
volumes:
  local_folder:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}
