name: Nightly Earthly Build

on:
  schedule:
    - cron: '0 0 * * *' # every night at midnight
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Earthly
      run: |
        sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'
        
    - name: Run Earthly Build
      run: |
        export VERSION=$(wget -qO- https://www.crushftp.com/version11_build.html | head -n 1 | awk '{print $2}' | grep -v selected)
        echo "Version is $VERSION"
        earthly --push +build-all
