name: Nightly Earthly Build

on:
  schedule:
    - cron: '0 */2 * * *' # every night at midnight
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Keep Workflow Alive
      run: |
        echo "Last run: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" > .github/workflows/last_run.txt
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git add .github/workflows/last_run.txt
        git commit -m "Keep workflow active - $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || exit 0
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Earthly
      run: |
        sudo apt update
        sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'
        sudo apt-get install qemu-system binfmt-support qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker stop earthly-buildkitd || true
    - name: Log into Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Run Earthly Build
      run: |
        export VERSION=$(wget -qO- https://www.crushftp.com/version11_build.html | head -n 1 | awk '{print $2}' | grep -v selected)
        echo "Version is $VERSION"
        export CURRENT_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        earthly --no-cache --push +build-all --VERSION=${VERSION} --RFC_DATE_TIME=${CURRENT_DATE}
